id = "codesandbox-theme"
name = "CodeSandbox Theme"
schema_version = 1
version = "0.0.2"
authors = ["Martin Ryberg Laude <martin@mrlaude.com>"]
description = "An unofficial CodeSandbox theme for Zed"
repository = "https://github.com/martinryberglaude/zed-theme-codesandbox"
